---
title: "Group3"
author: "Andrea Dest"
date: "10/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

__Load in Lyrics Data__
```{r}
library(tidyverse)
library(data.table)
library(ggplot2)
library(dplyr)
library(viridis)
lyrics_swift <- fread("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-29/taylor_swift_lyrics.csv", header =T)

```

Make a Boxplot to show number of words in each Album 
```{r}
lyrics_swift <- mutate(lyrics_swift, total_words = sapply(strsplit(lyrics_swift$Lyrics, " "), length))
total_word_plot <- ggplot(lyrics_swift, aes(x=Album, y=total_words)) + geom_boxplot() + ylab("Total Words") + ggtitle("Total Words by Album")
total_word_plot + geom_point(stat = "summary", fun="mean", color="red", size =2)
```

Make a graph to visualize pronouns used in each album
```{r}
pronouns <- lyrics_swift %>%
  mutate(her=(str_count(Lyrics, "her"))) %>%
  mutate(he=(str_count(Lyrics, "he"))) %>%
  mutate(they=(str_count(Lyrics, "they"))) %>%
  mutate(them=(str_count(Lyrics, "them"))) %>%
  mutate(she=(str_count(Lyrics, "she"))) %>%
  mutate(him=(str_count(Lyrics, "him"))) %>%
  mutate(me=(str_count(Lyrics, "me"))) %>%
  mutate(I=(str_count(Lyrics, "I"))) %>%
  pivot_longer(her:I, names_to = "pronoun_type", values_to="values") %>%
  mutate(type = case_when(xor(pronoun_type == "her", pronoun_type == "she") ~ "female",
                         xor(pronoun_type == "he", pronoun_type == "him") ~ "male", 
                         xor(pronoun_type == "they", pronoun_type == "them") ~ "non binary",
                         xor(pronoun_type == "I", pronoun_type == "me") ~ "I"
))

pronoun_plot <- ggplot(pronouns, aes(x=Title, y=values, size = values)) + geom_point(alpha =0.7, aes(color = pronoun_type)) + scale_size(range = c(.1, 3)) + ggtitle("Use of Pronouns by Type") + ylab("Total Number of Each Pronoun") + xlab("Songs") + theme(legend.position="bottom") + theme(axis.text.x=element_blank())

pronoun_plot + facet_grid(type~Album, scales ="free_y")
```

